shoulder:
  ID: 1
  Return_Delay_Time: 0
  # Operating_Mode: 3
  # Profile_Acceleration: 0
  # Profile_Velocity: 0
arm:
  ID: 2
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
forearm:
  ID: 3
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
wrist:
  ID: 4
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
gripper:
  ID: 5
  Return_Delay_Time: 0
#   Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
