controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: standup