arm_1_joint:
  ID: 1
  Return_Delay_Time: 0
  # Operating_Mode: 3
  # Profile_Acceleration: 0
  # Profile_Velocity: 0
arm_2_joint:
  ID: 2
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
arm_3_joint:
  ID: 3
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
arm_4_joint:
  ID: 4
  Return_Delay_Time: 0
  # Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
gripper_joint:
  ID: 5
  Return_Delay_Time: 0
#   Operating_Mode: 3
#   Profile_Acceleration: 0
#   Profile_Velocity: 0
